# Generated by Django 4.2.16 on 2024-11-21 05:25

import articles.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('create_at', models.IntegerField(default=articles.models.ts_now)),
                ('update_at', models.IntegerField(default=articles.models.ts_now)),
            ],
        ),
    ]
